task:
  name: Build
  persistent_worker: {}
  env:
    USE_CCACHE: 1
    CIRRUS_WORKING_DIR: /tmp/$CIRRUS_REPO_NAME
  clone_script:
    - df -h
    - free -h
    - python
    - mkdir ~/bin && PATH=~/bin:$PATH && curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+x ~/bin/repo
    - repo init -u https://github.com/Evolution-X/manifest -b tiramisu || true
  sync_script:
    - rm -rf .repo/local_manifests || true
    - git clone https://github.com/galang8664/local_manifest.git --depth 1 -b evoxr .repo/local_manifests
    - repo sync
  build_script:
    - . build/envsetup.sh
    - lunch evolution_lancelot-userdebug
    - mka evolution
  ccache_stats_script:
    - ccache -s
  upload_script: |
    up() {
      curl --upload-file $1 https://transfer.sh/$(basename $1); echo
      # 14 days, 10 GB limit
    }

    up out/target/product/lava/*.zip
