env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history

task:
  name: Test
  skip: $CIRRUS_BRANCH == 'main'
  only_if: $CIRRUS_REPO_OWNER == 'galang8664'
  timeout_in: 2m
  persistent_worker:
    labels:
      name: lang
    isolation:
      container:
        image: apon77/aosp:latest
        cpu: 2
        memory: 4G

  env_script:
    - env
  show_script:
    - cat $CIRRUS_WORKING_DIR/build_rom.sh
  test_script:
    - set -e
    - curl -Ls https://raw.githubusercontent.com/ROM-builders/temporary/main/test.sh | bash
